LLM:
  client: ollama
  model: llama3.2:3b  #gemma3:4b
  temperature: 0.85
  top_p: 1.0
  seed: 42

Gemini:
  model: gemini-2.5-flash
  temperature: 0.85
  top_p: 0.9

Encoder:
  model_name: dmis-lab/biobert-v1.1
  device: cuda

Create:
  Batch_size: 10
  Limit: null
  Resume: True
  max_parallel_chunks: 4
  max_parallel_files: 4

Insert:
  Batch_size: 100
  Limit: null
  Resume: False

Qdrant:
  timeout: 300 
  search_batch_size: 10 

Ollama:
  base_port: 11434
  num_ports: 4